# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy
from scrapy import Field

class AnixProduct(scrapy.Item):
    product_url = Field()
    cat_url = Field()

class AnixItem(scrapy.Item):
    manufacturer = Field()
    Brand = Field()
    manufacturer_number = Field()
    item_number = Field()
    upc = Field()
    unspsc = Field()
    product_name = Field()
    item_detailed = Field()
    package_size = Field()
    Order_Unit = Field()    
    minimum_quantity = Field()
    Currency_Code = Field()
    Without_Tax = Field()
    VAT= Field()
    msrp_list_price = Field()
    retail_price_your_price = Field()
    discount_you_save_amount = Field()
    discount_you_save_percentage = Field()
    volume_price_1  = Field()
    volume_for_discount_1  = Field()
    volume_discount_1  = Field()
    volume_price_2  = Field()
    volume_for_discount_2  = Field()
    volume_discount_2  = Field()
    volume_price_3  = Field()
    volume_for_discount_3  = Field()
    volume_discount_3  = Field()
    volume_price_4  = Field()
    volume_for_discount_4  = Field()
    volume_discount_4  = Field()
    volume_price_5  = Field()
    volume_for_discount_5  = Field()
    volume_discount_5  = Field()
    volume_price_6  = Field()
    volume_for_discount_6  = Field()
    volume_discount_6  = Field()
    volume_price_7  = Field()
    volume_for_discount_7  = Field()
    volume_discount_7  = Field()
    volume_price_8  = Field()
    volume_for_discount_8  = Field()
    volume_discount_8  = Field()
    volume_price_9  = Field()
    volume_for_discount_9  = Field()
    volume_discount_9  = Field()
    volume_price_10  = Field()
    volume_for_discount_10  = Field()
    volume_discount_10  = Field()
    product_attributes_technical_specs = Field()
    features = Field()
    specification = Field()
    applications = Field()
    caution = Field()
    in_stock = Field()
    category = Field()
    sub_category = Field()
    country_of_origin = Field()
    catalog = Field()
    guarantee_information = Field()
    shipping_information = Field()
    path = Field()
    source_url = Field()
    cross_referencing_product_url = Field()
    cross_referencing_product_name = Field()
    private_label = Field()
    attribute_type_1 = Field()
    attribute_type_2 = Field()
    attribute_type_3 = Field()
    attribute_type_4 = Field()
    attribute_type_5 = Field()
    attribute_type_6 = Field()
    attribute_type_7 = Field()
    attribute_type_8 = Field()
    attribute_type_9 = Field()
    attribute_type_10 = Field()

    attribute_value_1 = Field()
    attribute_value_2 = Field()
    attribute_value_3 = Field()
    attribute_value_4 = Field()
    attribute_value_5 = Field()
    attribute_value_6 = Field()
    attribute_value_7 = Field()
    attribute_value_8 = Field()
    attribute_value_9 = Field()
    attribute_value_10 = Field()

    

    attribute_type_11 = Field()
    attribute_type_12 = Field()
    attribute_type_13 = Field()
    attribute_type_14 = Field()
    attribute_type_15 = Field()
    attribute_type_16 = Field()
    attribute_type_17 = Field()
    attribute_type_18 = Field()
    attribute_type_19 = Field()
    attribute_type_20 = Field()

    attribute_value_11 = Field()
    attribute_value_12 = Field()
    attribute_value_13 = Field()
    attribute_value_14 = Field()
    attribute_value_15 = Field()
    attribute_value_16 = Field()
    attribute_value_17 = Field()
    attribute_value_18 = Field()
    attribute_value_19 = Field()
    attribute_value_20 = Field()




    attribute_type_21 = Field()
    attribute_type_22 = Field()
    attribute_type_23 = Field()
    attribute_type_24 = Field()
    attribute_type_25 = Field()
    attribute_type_26 = Field()
    attribute_type_27 = Field()
    attribute_type_28 = Field()
    attribute_type_29 = Field()
    attribute_type_30 = Field()

    attribute_value_21 = Field()
    attribute_value_22 = Field()
    attribute_value_23 = Field()
    attribute_value_24 = Field()
    attribute_value_25 = Field()
    attribute_value_26 = Field()
    attribute_value_27 = Field()
    attribute_value_28 = Field()
    attribute_value_29 = Field()
    attribute_value_30 = Field()




    attribute_type_31 = Field()
    attribute_type_32 = Field()
    attribute_type_33 = Field()
    attribute_type_34 = Field()
    attribute_type_35 = Field()
    attribute_type_36 = Field()
    attribute_type_37 = Field()
    attribute_type_38 = Field()
    attribute_type_39 = Field()
    attribute_type_40 = Field()

    attribute_value_31 = Field()
    attribute_value_32 = Field()
    attribute_value_33 = Field()
    attribute_value_34 = Field()
    attribute_value_35 = Field()
    attribute_value_36 = Field()
    attribute_value_37 = Field()
    attribute_value_38 = Field()
    attribute_value_39 = Field()
    attribute_value_40 = Field()



    attribute_type_41 = Field()
    attribute_type_42 = Field()
    attribute_type_43 = Field()
    attribute_type_44 = Field()
    attribute_type_45 = Field()
    attribute_type_46 = Field()
    attribute_type_47 = Field()
    attribute_type_48 = Field()
    attribute_type_49 = Field()
    attribute_type_50 = Field()

    attribute_value_41 = Field()
    attribute_value_42 = Field()
    attribute_value_43 = Field()
    attribute_value_44 = Field()
    attribute_value_45 = Field()
    attribute_value_46 = Field()
    attribute_value_47 = Field()
    attribute_value_48 = Field()
    attribute_value_49 = Field()
    attribute_value_50 = Field()


